### PR TITLE
owned by hydra maybe

### PR DESCRIPTION
**Pull request by staccDOTsol**
it builds? dunno about rest

back to other WIPs

### CODE REVIEW

**Comment by ChewingGlass** [comment]
This seems... unsafe haha. The hydra wallet should be owned by the system program, just not the hydra top level pda

**Comment by staccDOTsol** [comment]
Hey I wasn't gonna critique the og design lol

**Comment by ChewingGlass** [comment]
Closing since no movement on this in a while

**Comment by staccDOTsol** [comment]
Goodmorning @ChewingGlass hope you are well, hope you are landed.

image
image

image


@austbot I'd like to move this thread here.

**Comment by staccDOTsol** [comment]
happy Monday and all that jazz @austbot @ChewingGlass trust you folks are well rested

sup here?

I am traveling all day

would appreciate resolution as you're able

**Pull request closed without merging**
