### PR TITLE
Feature/chat create chat

### PR DESCRIPTION
**Pull request by bryzettler**

### CODE REVIEW

**Comment by staccDOTsol** [comment]
ayy y'all did it while I was napping :( :( :(

**Comment by bryzettler** [comment]
Im not sure why tests dont pass here
Screen Shot 2022-07-29 at 3 07 56 PM

**Review by ChewingGlass — APPROVED** [review]

**Comment by staccDOTsol** [comment]
gm

sned it
push it

**Comment by staccDOTsol** [comment]
oops it is still broken

bug bounntyyy

image

**Pull request merged**
